FROM php:7.4-fpm
RUN apt-get update && apt-get install -y \
curl \
wget \
git \
unzip \
libzip-dev \
libonig-dev \
libfreetype6-dev \
libjpeg62-turbo-dev \
libxslt-dev \
libicu-dev \
libmcrypt-dev \
libxml2-dev \
&& docker-php-ext-install -j$(nproc) iconv mbstring mysqli pdo_mysql zip
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-install xsl
RUN docker-php-ext-install soap

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


#Add custtom php ini setting to other settings
ADD ./docker/local/config/php/* /usr/local/etc/php/conf.d/

USER 1000
